# Generated by Django 5.2.9 on 2025-12-18 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.service')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.vet')),
            ],
            options={
                'unique_together': {('vet', 'service')},
            },
        ),
    ]
