# Generated by Django 5.2.9 on 2025-12-18 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_appointmentstatus_servicecategory_vetspecialization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Запись на приём', 'verbose_name_plural': 'Записи на приём'},
        ),
        migrations.AlterModelOptions(
            name='appointmentstatus',
            options={'verbose_name': 'Статус записи', 'verbose_name_plural': 'Статусы записей'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Категория услуги', 'verbose_name_plural': 'Категории услуг'},
        ),
        migrations.AlterModelOptions(
            name='vet',
            options={'verbose_name': 'Ветеринар', 'verbose_name_plural': 'Ветеринары'},
        ),
        migrations.AlterModelOptions(
            name='vetservice',
            options={'verbose_name': 'Связь ветеринар-услуга', 'verbose_name_plural': 'Связи ветеринар-услуга'},
        ),
        migrations.AlterModelOptions(
            name='vetspecialization',
            options={'verbose_name': 'Специализация ветеринара', 'verbose_name_plural': 'Специализации ветеринаров'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(verbose_name='Дата и время приёма'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.pet', verbose_name='Питомец'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.appointmentstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.vet', verbose_name='Ветеринар'),
        ),
        migrations.AlterField(
            model_name='appointmentstatus',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Статус записи'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя питомца'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='clinic.client', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(max_length=50, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.servicecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория услуги'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя ветеринара'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vets/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.vetspecialization', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='vetservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='vetservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='vetservice',
            name='vet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.vet', verbose_name='Ветеринар'),
        ),
        migrations.AlterField(
            model_name='vetspecialization',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Специализация'),
        ),
    ]
